
package com.myschema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HumanResourceService", targetNamespace = "http://mycompany.com/hr/schemas", wsdlLocation = "http://localhost:8080/holidayService/holiday.wsdl")
public class HumanResourceService
    extends Service
{

    private final static URL HUMANRESOURCESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.myschema.HumanResourceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.myschema.HumanResourceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/holidayService/holiday.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/holidayService/holiday.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HUMANRESOURCESERVICE_WSDL_LOCATION = url;
    }

    public HumanResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HumanResourceService() {
        super(HUMANRESOURCESERVICE_WSDL_LOCATION, new QName("http://mycompany.com/hr/schemas", "HumanResourceService"));
    }

    /**
     * 
     * @return
     *     returns HumanResource
     */
    @WebEndpoint(name = "HumanResourceSoap11")
    public HumanResource getHumanResourceSoap11() {
        return super.getPort(new QName("http://mycompany.com/hr/schemas", "HumanResourceSoap11"), HumanResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HumanResource
     */
    @WebEndpoint(name = "HumanResourceSoap11")
    public HumanResource getHumanResourceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://mycompany.com/hr/schemas", "HumanResourceSoap11"), HumanResource.class, features);
    }

}
